[package]
name = "multi_ping"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
windows = { version = "0.59.0", features = ["Win32_NetworkManagement_IpHelper", "Win32_System_IO","Win32_Networking_WinSock"] }
